"""
Generate 10 sample logistics PDF documents for demo & testing.
Each PDF simulates a real maritime document with proper layout.
Used for: CLASSIFY_DOCUMENT_TEXT + AI_PARSE_DOCUMENT testing.

Run: pip install fpdf2 && python generate_sample_docs.py
Output: sample_documents/ folder with 10 PDFs
"""

from fpdf import FPDF
import os
from datetime import date, timedelta
import random

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "sample_documents")
os.makedirs(OUTPUT_DIR, exist_ok=True)


class LogisticsDoc(FPDF):
    def header_block(self, title, doc_no):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "", 10)
        self.cell(0, 6, f"Document No: {doc_no}", new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(5)

    def section(self, title):
        self.set_font("Helvetica", "B", 11)
        self.set_fill_color(230, 230, 230)
        self.cell(0, 7, f"  {title}", new_x="LMARGIN", new_y="NEXT", fill=True)
        self.set_font("Helvetica", "", 10)
        self.ln(2)

    def field(self, label, value):
        self.set_font("Helvetica", "B", 9)
        self.cell(50, 6, f"{label}:")
        self.set_font("Helvetica", "", 9)
        self.cell(0, 6, str(value), new_x="LMARGIN", new_y="NEXT")


def gen_commercial_invoice():
    pdf = LogisticsDoc()
    pdf.add_page()
    pdf.header_block("COMMERCIAL INVOICE", "INV-2024-VN-00567")
    pdf.section("Seller (Exporter)")
    pdf.field("Company", "VIETNAM COFFEE EXPORT JSC")
    pdf.field("Address", "123 Nguyen Hue St, District 1, Ho Chi Minh City, Vietnam")
    pdf.field("Tax ID", "VN-0301234567")
    pdf.section("Buyer (Importer)")
    pdf.field("Company", "TOKYO FOOD TRADING CO LTD")
    pdf.field("Address", "2-4-1 Marunouchi, Chiyoda-ku, Tokyo 100-0005, Japan")
    pdf.section("Invoice Details")
    pdf.field("Date", "2024-11-15")
    pdf.field("Terms", "CIF YOKOHAMA")
    pdf.field("Currency", "USD")
    pdf.field("B/L Reference", "MAEU1234567")
    pdf.section("Goods Description")
    pdf.field("Description", "ROBUSTA COFFEE BEANS, GRADE 1, SCREEN 16+")
    pdf.field("HS Code", "0901.11")
    pdf.field("Quantity", "1,200 BAGS (60 KG EACH)")
    pdf.field("Unit Price", "USD 2.45 / KG")
    pdf.field("Total Weight", "72,000 KGS NET")
    pdf.field("Total Amount", "USD 176,400.00")
    pdf.section("Payment")
    pdf.field("Method", "Irrevocable Letter of Credit")
    pdf.field("L/C No", "LC-2024-TFT-0089")
    pdf.field("Bank", "MUFG Bank, Tokyo Branch")
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 6, "Certified true and correct. Signed: Nguyen Van Minh, Export Manager", new_x="LMARGIN", new_y="NEXT")
    pdf.output(os.path.join(OUTPUT_DIR, "01_commercial_invoice.pdf"))


def gen_packing_list():
    pdf = LogisticsDoc()
    pdf.add_page()
    pdf.header_block("PACKING LIST", "PL-2024-VN-00567")
    pdf.section("Shipper")
    pdf.field("Company", "VIETNAM COFFEE EXPORT JSC")
    pdf.field("Invoice Ref", "INV-2024-VN-00567")
    pdf.section("Consignee")
    pdf.field("Company", "TOKYO FOOD TRADING CO LTD")
    pdf.section("Vessel / Voyage")
    pdf.field("Vessel", "EVER ACE")
    pdf.field("Voyage", "245E")
    pdf.field("Container", "MSCU7654321 (40HC)")
    pdf.section("Packing Details")
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(30, 6, "Marks", border=1)
    pdf.cell(60, 6, "Description", border=1)
    pdf.cell(30, 6, "Packages", border=1)
    pdf.cell(30, 6, "Gross Wt", border=1)
    pdf.cell(30, 6, "Net Wt", border=1, new_x="LMARGIN", new_y="NEXT")
    for i in range(1, 6):
        pdf.cell(30, 6, f"VCE/{i:03d}", border=1)
        pdf.cell(60, 6, "ROBUSTA COFFEE BEANS GR.1", border=1)
        pdf.cell(30, 6, "240 BAGS", border=1)
        pdf.cell(30, 6, "14,640 KGS", border=1)
        pdf.cell(30, 6, "14,400 KGS", border=1, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    pdf.field("Total Packages", "1,200 BAGS")
    pdf.field("Total Gross Weight", "73,200 KGS")
    pdf.field("Total Net Weight", "72,000 KGS")
    pdf.field("Measurement", "58.5 CBM")
    pdf.output(os.path.join(OUTPUT_DIR, "02_packing_list.pdf"))


def gen_certificate_of_origin():
    pdf = LogisticsDoc()
    pdf.add_page()
    pdf.header_block("CERTIFICATE OF ORIGIN", "CO-VN-2024-89012")
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 6, "Form AJ - ASEAN-Japan Comprehensive Economic Partnership (AJCEP)", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)
    pdf.section("Exporter")
    pdf.field("Company", "VIETNAM COFFEE EXPORT JSC")
    pdf.field("Country", "VIETNAM")
    pdf.section("Importer")
    pdf.field("Company", "TOKYO FOOD TRADING CO LTD")
    pdf.field("Country", "JAPAN")
    pdf.section("Goods")
    pdf.field("Description", "ROBUSTA COFFEE BEANS, GRADE 1")
    pdf.field("HS Code", "0901.11.10")
    pdf.field("Origin Criteria", "WO - Wholly Obtained")
    pdf.field("Gross Weight", "73,200 KGS")
    pdf.field("Invoice No", "INV-2024-VN-00567")
    pdf.field("Invoice Date", "2024-11-15")
    pdf.section("Certification")
    pdf.field("Issuing Authority", "Vietnam Chamber of Commerce and Industry (VCCI)")
    pdf.field("Issue Date", "2024-11-16")
    pdf.field("Issue Place", "Ho Chi Minh City")
    pdf.ln(10)
    pdf.cell(0, 6, "CERTIFIED: The goods described above originate in Vietnam.", new_x="LMARGIN", new_y="NEXT")
    pdf.output(os.path.join(OUTPUT_DIR, "03_certificate_of_origin.pdf"))


def gen_dg_declaration():
    pdf = LogisticsDoc()
    pdf.add_page()
    pdf.header_block("DANGEROUS GOODS DECLARATION", "DGD-2024-VN-00234")
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(255, 0, 0)
    pdf.cell(0, 8, "IMO DANGEROUS GOODS - MULTIMODAL TRANSPORT", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)
    pdf.section("Shipper")
    pdf.field("Company", "BINH DUONG CHEMICALS JSC")
    pdf.field("Emergency Contact", "+84-28-3822-0001 (24h)")
    pdf.section("Dangerous Goods Information")
    pdf.field("UN Number", "UN 1170")
    pdf.field("Proper Shipping Name", "ETHANOL (ETHYL ALCOHOL)")
    pdf.field("Class", "3 - Flammable Liquids")
    pdf.field("Packing Group", "II")
    pdf.field("Flash Point", "13C (closed cup)")
    pdf.field("Marine Pollutant", "No")
    pdf.field("EmS", "F-E, S-D")
    pdf.section("Packaging")
    pdf.field("Type", "Steel drums, UN certified")
    pdf.field("Quantity", "80 drums x 200L")
    pdf.field("Net Quantity", "16,000 Litres")
    pdf.field("Gross Weight", "14,200 KGS")
    pdf.section("Container")
    pdf.field("Container No", "HLXU4567890")
    pdf.field("Type", "20GP")
    pdf.field("Placard", "Class 3 diamond on all 4 sides")
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, "I declare the contents are fully and accurately described above.", new_x="LMARGIN", new_y="NEXT")
    pdf.output(os.path.join(OUTPUT_DIR, "04_dg_declaration.pdf"))


def gen_cargo_manifest():
    pdf = LogisticsDoc()
    pdf.add_page()
    pdf.header_block("CARGO MANIFEST", "MAN-VNSGN-2024-1115")
    pdf.section("Vessel Information")
    pdf.field("Vessel", "EVER ACE (IMO: 9839430)")
    pdf.field("Voyage", "245E")
    pdf.field("Port of Loading", "HO CHI MINH CITY (VNSGN)")
    pdf.field("Port of Discharge", "YOKOHAMA (JPYOK)")
    pdf.field("ETD", "2024-11-20")
    pdf.section("Cargo Summary")
    pdf.set_font("Helvetica", "", 8)
    headers = ["B/L No", "Shipper", "Consignee", "Containers", "Weight"]
    widths = [30, 45, 45, 30, 30]
    for h, w in zip(headers, widths):
        pdf.cell(w, 6, h, border=1)
    pdf.ln()
    data = [
        ("MAEU1234567", "VN COFFEE EXPORT", "TOKYO FOOD TRADING", "1x40HC", "73,200 KG"),
        ("MAEU1234568", "SAIGON SEAFOOD", "OSAKA IMPORTS", "1x40RF", "18,500 KG"),
        ("MAEU1234569", "MEKONG RICE", "NAGOYA TRADING", "2x20GP", "52,000 KG"),
        ("MAEU1234570", "VN CASHEW EXPORT", "KOBE NUTS INC", "1x20GP", "24,800 KG"),
        ("MAEU1234571", "BD CHEMICALS", "TOKYO CHEM CO", "1x20GP", "14,200 KG"),
    ]
    for row in data:
        for val, w in zip(row, widths):
            pdf.cell(w, 6, val, border=1)
        pdf.ln()
    pdf.ln(5)
    pdf.field("Total B/Ls", "5")
    pdf.field("Total Containers", "6 (3x20GP + 2x40HC + 1x40RF)")
    pdf.field("Total Weight", "182,700 KGS")
    pdf.output(os.path.join(OUTPUT_DIR, "05_cargo_manifest.pdf"))


def gen_booking_confirmation():
    pdf = LogisticsDoc()
    pdf.add_page()
    pdf.header_block("BOOKING CONFIRMATION", "BK-MSC-2024-98765")
    pdf.section("Carrier")
    pdf.field("Shipping Line", "Mediterranean Shipping Company (MSC)")
    pdf.field("Service", "DRAGON EXPRESS (Far East - Japan)")
    pdf.section("Booking Details")
    pdf.field("Shipper", "VIETNAM COFFEE EXPORT JSC")
    pdf.field("Commodity", "COFFEE BEANS (non-DG)")
    pdf.field("Container", "1 x 40HC (MSCU to be assigned)")
    pdf.field("Weight", "Approx. 24,000 KGS")
    pdf.field("Port of Loading", "HO CHI MINH CITY (VNSGN)")
    pdf.field("Port of Discharge", "YOKOHAMA (JPYOK)")
    pdf.section("Schedule")
    pdf.field("Vessel", "MSC IRINA")
    pdf.field("Voyage", "FE2411E")
    pdf.field("CY Cut-off", "2024-11-18 17:00 LT")
    pdf.field("SI Cut-off", "2024-11-17 12:00 LT")
    pdf.field("ETD", "2024-11-20")
    pdf.field("ETA", "2024-11-28")
    pdf.section("Terms")
    pdf.field("Freight", "PREPAID")
    pdf.field("Ocean Freight", "USD 1,850 per 40HC")
    pdf.field("THC Origin", "USD 150")
    pdf.field("Documentation Fee", "USD 50")
    pdf.output(os.path.join(OUTPUT_DIR, "06_booking_confirmation.pdf"))


def gen_delivery_order():
    pdf = LogisticsDoc()
    pdf.add_page()
    pdf.header_block("DELIVERY ORDER", "DO-JPYOK-2024-4567")
    pdf.section("To: Terminal Operator")
    pdf.field("Terminal", "Yokohama Container Terminal (YCT)")
    pdf.field("Date", "2024-11-29")
    pdf.section("Please deliver the following cargo to")
    pdf.field("Consignee", "TOKYO FOOD TRADING CO LTD")
    pdf.field("Notify", "Same as consignee")
    pdf.section("Cargo Details")
    pdf.field("B/L Number", "MAEU1234567")
    pdf.field("Container", "MSCU7654321 (40HC)")
    pdf.field("Seal", "MSC-SL-889900")
    pdf.field("Description", "ROBUSTA COFFEE BEANS")
    pdf.field("Weight", "73,200 KGS")
    pdf.field("Packages", "1,200 BAGS")
    pdf.section("Release Authorization")
    pdf.field("Freight Status", "PREPAID - RELEASED")
    pdf.field("Customs Status", "CLEARED (Entry No: YOK-2024-112233)")
    pdf.field("Authorized By", "MSC Japan - Yokohama Office")
    pdf.ln(10)
    pdf.cell(0, 6, "This D/O is valid for 7 days from date of issue.", new_x="LMARGIN", new_y="NEXT")
    pdf.output(os.path.join(OUTPUT_DIR, "07_delivery_order.pdf"))


def gen_shipping_instruction():
    pdf = LogisticsDoc()
    pdf.add_page()
    pdf.header_block("SHIPPING INSTRUCTION", "SI-2024-VN-00567")
    pdf.section("From: Shipper")
    pdf.field("Company", "VIETNAM COFFEE EXPORT JSC")
    pdf.field("Contact", "Ms. Tran Thi Lan - export@vncoffee.com.vn")
    pdf.section("To: Carrier")
    pdf.field("Shipping Line", "Maersk Line")
    pdf.field("Booking No", "BK-MAEU-2024-56789")
    pdf.section("B/L Instructions")
    pdf.field("B/L Type", "ORIGINAL (3/3)")
    pdf.field("Freight Terms", "PREPAID")
    pdf.field("Shipper on B/L", "VIETNAM COFFEE EXPORT JSC")
    pdf.field("Consignee on B/L", "TO ORDER OF MUFG BANK")
    pdf.field("Notify Party", "TOKYO FOOD TRADING CO LTD")
    pdf.section("Cargo Details")
    pdf.field("Description", "ROBUSTA COFFEE BEANS GRADE 1 SCREEN 16+")
    pdf.field("HS Code", "0901.11")
    pdf.field("Marks & Numbers", "VCE/001 - VCE/1200")
    pdf.field("Packages", "1,200 JUTE BAGS")
    pdf.field("Gross Weight", "73,200 KGS")
    pdf.field("Measurement", "58.5 CBM")
    pdf.output(os.path.join(OUTPUT_DIR, "08_shipping_instruction.pdf"))


def gen_arrival_notice():
    pdf = LogisticsDoc()
    pdf.add_page()
    pdf.header_block("ARRIVAL NOTICE", "AN-JPYOK-2024-8901")
    pdf.section("Notify Party")
    pdf.field("Company", "TOKYO FOOD TRADING CO LTD")
    pdf.field("Attention", "Import Department")
    pdf.section("Vessel Arrival")
    pdf.field("Vessel", "EVER ACE (IMO: 9839430)")
    pdf.field("Voyage", "245E")
    pdf.field("ETA Yokohama", "2024-11-28 06:00 LT")
    pdf.field("Berth", "YCT Berth D-4")
    pdf.section("Shipment Details")
    pdf.field("B/L Number", "MAEU1234567")
    pdf.field("Shipper", "VIETNAM COFFEE EXPORT JSC")
    pdf.field("Container", "MSCU7654321 (40HC)")
    pdf.field("Description", "ROBUSTA COFFEE BEANS")
    pdf.field("Weight", "73,200 KGS")
    pdf.section("Charges Due at Destination")
    pdf.field("THC Destination", "JPY 35,000")
    pdf.field("D/O Fee", "JPY 5,000")
    pdf.field("CFS Charge", "N/A (FCL)")
    pdf.field("Total Due", "JPY 40,000")
    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, "Please arrange customs clearance and collect D/O within 5 free days.", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, "Demurrage: JPY 5,000/day after free time.", new_x="LMARGIN", new_y="NEXT")
    pdf.output(os.path.join(OUTPUT_DIR, "09_arrival_notice.pdf"))


def gen_health_certificate():
    pdf = LogisticsDoc()
    pdf.add_page()
    pdf.header_block("HEALTH / PHYTOSANITARY CERTIFICATE", "HC-VN-MARD-2024-5678")
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 6, "Ministry of Agriculture and Rural Development - Plant Protection Department", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)
    pdf.section("Exporter")
    pdf.field("Company", "MEKONG RICE TRADING CO LTD")
    pdf.field("Country", "Vietnam")
    pdf.section("Importer")
    pdf.field("Company", "SEOUL TRADING COMPANY")
    pdf.field("Country", "South Korea")
    pdf.section("Product Information")
    pdf.field("Product", "JASMINE RICE 5% BROKEN, NEW CROP 2024")
    pdf.field("HS Code", "1006.30")
    pdf.field("Quantity", "500 MT (METRIC TONS)")
    pdf.field("Packaging", "50 KG PP bags, palletized")
    pdf.field("Origin", "An Giang Province, Vietnam")
    pdf.section("Inspection Results")
    pdf.field("Inspection Date", "2024-11-14")
    pdf.field("Moisture Content", "13.8% (max 14%: PASS)")
    pdf.field("Foreign Matter", "0.02% (max 0.1%: PASS)")
    pdf.field("Pest Inspection", "No live insects detected: PASS")
    pdf.field("Aflatoxin B1", "< 2 ppb (max 5 ppb: PASS)")
    pdf.field("Overall Result", "PASSED - FIT FOR EXPORT")
    pdf.ln(8)
    pdf.cell(0, 6, "Certified by: Dr. Nguyen Thanh Hai, Chief Inspector", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, "MARD License No: PPD-HCM-2024-001", new_x="LMARGIN", new_y="NEXT")
    pdf.output(os.path.join(OUTPUT_DIR, "10_health_certificate.pdf"))


if __name__ == "__main__":
    print("Generating sample logistics documents...")
    gen_commercial_invoice()
    print("  1/10 Commercial Invoice")
    gen_packing_list()
    print("  2/10 Packing List")
    gen_certificate_of_origin()
    print("  3/10 Certificate of Origin")
    gen_dg_declaration()
    print("  4/10 DG Declaration")
    gen_cargo_manifest()
    print("  5/10 Cargo Manifest")
    gen_booking_confirmation()
    print("  6/10 Booking Confirmation")
    gen_delivery_order()
    print("  7/10 Delivery Order")
    gen_shipping_instruction()
    print("  8/10 Shipping Instruction")
    gen_arrival_notice()
    print("  9/10 Arrival Notice")
    gen_health_certificate()
    print("  10/10 Health/Phytosanitary Certificate")
    print(f"\nDone! Files saved to: {OUTPUT_DIR}/")
    print("Upload to Snowflake stage: PUT file://sample_documents/*.pdf @MENDIX_APP.AGENTS.BL_DOCUMENTS_STAGE")
