-- =====================================================
-- LOGISTICS 4-PHASE DATA PIPELINE - COMPLETE SETUP
-- =====================================================
-- Created: 2026-06-22
-- Description: Full deployment script for logistics data pipeline
--              Phase 1→2→3→4 automatic synchronization
-- =====================================================

-- =====================================================
-- STEP 1: CREATE DATABASE & SCHEMAS
-- =====================================================
CREATE DATABASE IF NOT EXISTS LOGISTICS_DB;

CREATE SCHEMA IF NOT EXISTS LOGISTICS_DB.PHASE1_SCHEMA;
CREATE SCHEMA IF NOT EXISTS LOGISTICS_DB.PHASE2_SCHEMA;
CREATE SCHEMA IF NOT EXISTS LOGISTICS_DB.PHASE3_SCHEMA;
CREATE SCHEMA IF NOT EXISTS LOGISTICS_DB.PHASE4_SCHEMA;
CREATE SCHEMA IF NOT EXISTS LOGISTICS_DB.COMMON;

-- =====================================================
-- STEP 2: CREATE TABLES
-- =====================================================

-- PHASE 1: Bill of Lading Extractor (AI-powered PDF extraction)
CREATE OR REPLACE TABLE LOGISTICS_DB.PHASE1_SCHEMA.BL_EXTRACTS (
    -- Primary Keys
    EXTRACT_ID VARCHAR(50) PRIMARY KEY,
    BL_NUMBER VARCHAR(100) NOT NULL,
    
    -- PDF Information
    PDF_FILE_NAME VARCHAR(500),
    PDF_UPLOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PDF_FILE_SIZE_KB NUMBER(10,2),
    
    -- AI Extraction Results (JSON format from Cortex)
    EXTRACTED_DATA VARIANT,
    
    -- Key Fields (flatten from VARIANT for faster queries)
    SHIPPER_NAME VARCHAR(500),
    CONSIGNEE_NAME VARCHAR(500),
    CONTAINER_NUMBER VARCHAR(50),
    VESSEL_NAME VARCHAR(200),
    VOYAGE_NUMBER VARCHAR(50),
    PORT_OF_LOADING VARCHAR(200),
    PORT_OF_DISCHARGE VARCHAR(200),
    ETD DATE,
    ETA DATE,
    CARGO_DESCRIPTION VARCHAR(2000),
    GROSS_WEIGHT NUMBER(15,2),
    MEASUREMENT NUMBER(15,2),
    
    -- AI Confidence Scores
    CONFIDENCE_SCORE NUMBER(5,2),
    NEEDS_HUMAN_REVIEW BOOLEAN DEFAULT FALSE,
    
    -- Human Review Status
    REVIEW_STATUS VARCHAR(20) DEFAULT 'PENDING',
    REVIEWED_BY VARCHAR(100),
    REVIEWED_AT TIMESTAMP_NTZ,
    REVIEW_NOTES VARCHAR(2000),
    
    -- Processing Status
    PROCESSING_STATUS VARCHAR(30) DEFAULT 'EXTRACTED',
    SYNC_TO_PHASE2_AT TIMESTAMP_NTZ,
    
    -- Audit Fields
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100)
);

-- PHASE 2: Land Transportation & Gate Management
CREATE OR REPLACE TABLE LOGISTICS_DB.PHASE2_SCHEMA.GATE_TRANSACTIONS (
    -- Primary Keys
    TRANSACTION_ID VARCHAR(50) PRIMARY KEY,
    CONTAINER_NUMBER VARCHAR(50) NOT NULL,
    
    -- Link to Phase 1
    BL_NUMBER VARCHAR(100),
    EXTRACT_ID VARCHAR(50),
    
    -- Truck & Driver Information
    TRUCK_LICENSE_PLATE VARCHAR(20) NOT NULL,
    DRIVER_PHONE VARCHAR(20),
    DRIVER_NAME VARCHAR(200),
    TRUCKING_COMPANY VARCHAR(300),
    
    -- Gate Transaction Details
    TRANSACTION_TYPE VARCHAR(20),
    GATE_NUMBER VARCHAR(10),
    GATE_IN_TIME TIMESTAMP_NTZ,
    GATE_OUT_TIME TIMESTAMP_NTZ,
    DURATION_MINUTES NUMBER(10,2),
    
    -- Container Status
    CONTAINER_TYPE VARCHAR(20),
    CONTAINER_CONDITION VARCHAR(20),
    SEAL_NUMBER VARCHAR(50),
    
    -- Location Assignment
    ASSIGNED_LOCATION VARCHAR(50),
    WAREHOUSE_ID VARCHAR(50),
    
    -- Zalo Bot Integration
    ZALO_MESSAGE_SENT BOOLEAN DEFAULT FALSE,
    ZALO_MESSAGE_TIMESTAMP TIMESTAMP_NTZ,
    ZALO_MESSAGE_ID VARCHAR(100),
    
    -- Anonymous Portal Info
    QR_CODE_SCANNED_AT TIMESTAMP_NTZ,
    PORTAL_SESSION_ID VARCHAR(100),
    
    -- Processing Status
    PROCESSING_STATUS VARCHAR(30) DEFAULT 'GATE_IN_RECORDED',
    SYNC_TO_PHASE3_AT TIMESTAMP_NTZ,
    
    -- Audit Fields
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100)
);

-- PHASE 3: Warehouse & Terminal Management
CREATE OR REPLACE TABLE LOGISTICS_DB.PHASE3_SCHEMA.WAREHOUSE_INVENTORY (
    -- Primary Keys
    INVENTORY_ID VARCHAR(50) PRIMARY KEY,
    CONTAINER_NUMBER VARCHAR(50) NOT NULL,
    
    -- Link to Previous Phases
    BL_NUMBER VARCHAR(100),
    EXTRACT_ID VARCHAR(50),
    TRANSACTION_ID VARCHAR(50),
    
    -- Warehouse Location
    WAREHOUSE_CODE VARCHAR(10) NOT NULL,
    WAREHOUSE_NAME VARCHAR(200),
    ZONE VARCHAR(20),
    LOCATION_CODE VARCHAR(50),
    ROW_NUMBER VARCHAR(10),
    BAY_NUMBER VARCHAR(10),
    TIER_NUMBER VARCHAR(10),
    
    -- Container/Cargo Details
    CARGO_TYPE VARCHAR(100),
    WEIGHT_KG NUMBER(15,2),
    VOLUME_CBM NUMBER(15,2),
    TEMPERATURE_REQUIREMENT NUMBER(5,2),
    
    -- Yard Allocation Algorithm Results
    ALLOCATED_BY_AI BOOLEAN DEFAULT FALSE,
    ALLOCATION_SCORE NUMBER(5,2),
    OPTIMAL_POSITION BOOLEAN DEFAULT FALSE,
    RESTACKING_REQUIRED BOOLEAN DEFAULT FALSE,
    RESTACKING_COUNT NUMBER(5,0) DEFAULT 0,
    
    -- Stock Status
    STOCK_STATUS VARCHAR(30) DEFAULT 'IN_STOCK',
    STOCK_IN_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STOCK_OUT_DATE TIMESTAMP_NTZ,
    
    -- Mobile App Offline Sync
    LAST_SCANNED_AT TIMESTAMP_NTZ,
    SCANNED_BY VARCHAR(100),
    SCANNED_DEVICE_ID VARCHAR(100),
    OFFLINE_SYNC_FLAG BOOLEAN DEFAULT FALSE,
    SYNCED_TO_CLOUD_AT TIMESTAMP_NTZ,
    
    -- Vessel Schedule
    VESSEL_ETD DATE,
    LOADING_PRIORITY NUMBER(3,0),
    
    -- Processing Status
    PROCESSING_STATUS VARCHAR(30) DEFAULT 'STORED',
    SYNC_TO_PHASE4_AT TIMESTAMP_NTZ,
    
    -- Audit Fields
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100)
);

-- PHASE 4: SAP ERP Integration & Data Cloud
CREATE OR REPLACE TABLE LOGISTICS_DB.PHASE4_SCHEMA.SAP_INTEGRATION (
    -- Primary Keys
    SAP_INTEGRATION_ID VARCHAR(50) PRIMARY KEY,
    
    -- Link to All Previous Phases
    BL_NUMBER VARCHAR(100) NOT NULL,
    EXTRACT_ID VARCHAR(50),
    TRANSACTION_ID VARCHAR(50),
    INVENTORY_ID VARCHAR(50),
    CONTAINER_NUMBER VARCHAR(50),
    
    -- SAP Document Numbers
    SAP_MATERIAL_DOCUMENT VARCHAR(20),
    SAP_SALES_ORDER VARCHAR(20),
    SAP_DELIVERY_NOTE VARCHAR(20),
    SAP_INVOICE_NUMBER VARCHAR(20),
    SAP_GOODS_RECEIPT VARCHAR(20),
    
    -- Financial Data
    INVOICE_AMOUNT NUMBER(15,2),
    CURRENCY VARCHAR(3) DEFAULT 'VND',
    PAYMENT_STATUS VARCHAR(20),
    PAYMENT_DATE DATE,
    
    -- SAP Integration Status
    SAP_SYNC_STATUS VARCHAR(30) DEFAULT 'PENDING',
    SAP_SYNC_ATTEMPT_COUNT NUMBER(3,0) DEFAULT 0,
    LAST_SYNC_ATTEMPT_AT TIMESTAMP_NTZ,
    LAST_SYNC_SUCCESS_AT TIMESTAMP_NTZ,
    SAP_ERROR_MESSAGE VARCHAR(2000),
    
    -- SAP API Details
    SAP_RFC_FUNCTION VARCHAR(100),
    SAP_ODATA_ENDPOINT VARCHAR(500),
    SAP_REQUEST_PAYLOAD VARIANT,
    SAP_RESPONSE_PAYLOAD VARIANT,
    
    -- Zero-Copy SAP BDC Integration
    SAP_BDC_CONNECTED BOOLEAN DEFAULT FALSE,
    SAP_BDC_LAST_READ TIMESTAMP_NTZ,
    SAP_FINANCIAL_DATA VARIANT,
    
    -- Real-time Dashboard Flags
    DASHBOARD_VISIBLE BOOLEAN DEFAULT TRUE,
    EXECUTIVE_REPORT_INCLUDED BOOLEAN DEFAULT FALSE,
    
    -- Processing Status
    PROCESSING_STATUS VARCHAR(30) DEFAULT 'READY_FOR_SAP',
    FULLY_INTEGRATED BOOLEAN DEFAULT FALSE,
    
    -- Audit Fields
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100)
);

-- =====================================================
-- STEP 3: CREATE STREAMS (Change Data Capture)
-- =====================================================

CREATE OR REPLACE STREAM LOGISTICS_DB.PHASE1_SCHEMA.BL_EXTRACTS_STREAM
ON TABLE LOGISTICS_DB.PHASE1_SCHEMA.BL_EXTRACTS
APPEND_ONLY = FALSE
COMMENT = 'Track approved B/L extracts ready to sync to Phase 2';

CREATE OR REPLACE STREAM LOGISTICS_DB.PHASE2_SCHEMA.GATE_TRANSACTIONS_STREAM
ON TABLE LOGISTICS_DB.PHASE2_SCHEMA.GATE_TRANSACTIONS
APPEND_ONLY = FALSE
COMMENT = 'Track gate-in transactions ready to sync to Phase 3 warehouse';

CREATE OR REPLACE STREAM LOGISTICS_DB.PHASE3_SCHEMA.WAREHOUSE_INVENTORY_STREAM
ON TABLE LOGISTICS_DB.PHASE3_SCHEMA.WAREHOUSE_INVENTORY
APPEND_ONLY = FALSE
COMMENT = 'Track warehouse inventory ready to sync to Phase 4 SAP';

-- =====================================================
-- STEP 4: CREATE TASKS (Automated Sync Pipeline)
-- =====================================================

-- TASK 1: Sync Phase 1 → Phase 2
CREATE OR REPLACE TASK LOGISTICS_DB.COMMON.SYNC_PHASE1_TO_PHASE2
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('LOGISTICS_DB.PHASE1_SCHEMA.BL_EXTRACTS_STREAM')
AS
INSERT INTO LOGISTICS_DB.PHASE2_SCHEMA.GATE_TRANSACTIONS (
    TRANSACTION_ID, CONTAINER_NUMBER, BL_NUMBER, EXTRACT_ID,
    CONTAINER_TYPE, PROCESSING_STATUS, CREATED_AT, CREATED_BY
)
SELECT 
    'TXN-' || EXTRACT_ID || '-' || UNIFORM(1000, 9999, RANDOM())::VARCHAR,
    CONTAINER_NUMBER, BL_NUMBER, EXTRACT_ID,
    'STANDARD', 'AWAITING_GATE_IN',
    CURRENT_TIMESTAMP(), 'SYSTEM_AUTO_SYNC'
FROM LOGISTICS_DB.PHASE1_SCHEMA.BL_EXTRACTS_STREAM
WHERE METADATA$ACTION = 'INSERT' 
  AND REVIEW_STATUS = 'APPROVED'
  AND PROCESSING_STATUS = 'REVIEWED'
  AND SYNC_TO_PHASE2_AT IS NULL;

-- TASK 2: Sync Phase 2 → Phase 3
CREATE OR REPLACE TASK LOGISTICS_DB.COMMON.SYNC_PHASE2_TO_PHASE3
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('LOGISTICS_DB.PHASE2_SCHEMA.GATE_TRANSACTIONS_STREAM')
AS
INSERT INTO LOGISTICS_DB.PHASE3_SCHEMA.WAREHOUSE_INVENTORY (
    INVENTORY_ID, CONTAINER_NUMBER, BL_NUMBER, EXTRACT_ID, TRANSACTION_ID,
    WAREHOUSE_CODE, LOCATION_CODE, STOCK_STATUS, PROCESSING_STATUS,
    CREATED_AT, CREATED_BY
)
SELECT 
    'INV-' || TRANSACTION_ID || '-' || UNIFORM(1000, 9999, RANDOM())::VARCHAR,
    CONTAINER_NUMBER, BL_NUMBER, EXTRACT_ID, TRANSACTION_ID,
    'WH-' || UNIFORM(1, 7, RANDOM())::VARCHAR,
    ASSIGNED_LOCATION, 'IN_STOCK', 'AWAITING_ALLOCATION',
    CURRENT_TIMESTAMP(), 'SYSTEM_AUTO_SYNC'
FROM LOGISTICS_DB.PHASE2_SCHEMA.GATE_TRANSACTIONS_STREAM
WHERE METADATA$ACTION = 'INSERT' 
  AND TRANSACTION_TYPE = 'GATE_IN'
  AND GATE_IN_TIME IS NOT NULL
  AND SYNC_TO_PHASE3_AT IS NULL;

-- TASK 3: Sync Phase 3 → Phase 4
CREATE OR REPLACE TASK LOGISTICS_DB.COMMON.SYNC_PHASE3_TO_PHASE4
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('LOGISTICS_DB.PHASE3_SCHEMA.WAREHOUSE_INVENTORY_STREAM')
AS
INSERT INTO LOGISTICS_DB.PHASE4_SCHEMA.SAP_INTEGRATION (
    SAP_INTEGRATION_ID, BL_NUMBER, EXTRACT_ID, TRANSACTION_ID,
    INVENTORY_ID, CONTAINER_NUMBER, SAP_SYNC_STATUS, PROCESSING_STATUS,
    CREATED_AT, CREATED_BY
)
SELECT 
    'SAP-' || INVENTORY_ID || '-' || UNIFORM(1000, 9999, RANDOM())::VARCHAR,
    BL_NUMBER, EXTRACT_ID, TRANSACTION_ID,
    INVENTORY_ID, CONTAINER_NUMBER, 'PENDING', 'READY_FOR_SAP',
    CURRENT_TIMESTAMP(), 'SYSTEM_AUTO_SYNC'
FROM LOGISTICS_DB.PHASE3_SCHEMA.WAREHOUSE_INVENTORY_STREAM
WHERE METADATA$ACTION = 'INSERT' 
  AND STOCK_STATUS = 'IN_STOCK'
  AND SYNC_TO_PHASE4_AT IS NULL;

-- TASK 4: Update Phase 1 sync status
CREATE OR REPLACE TASK LOGISTICS_DB.COMMON.UPDATE_PHASE1_SYNC_STATUS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
AS
MERGE INTO LOGISTICS_DB.PHASE1_SCHEMA.BL_EXTRACTS t
USING (
    SELECT DISTINCT EXTRACT_ID
    FROM LOGISTICS_DB.PHASE2_SCHEMA.GATE_TRANSACTIONS
    WHERE CREATED_AT >= DATEADD(MINUTE, -10, CURRENT_TIMESTAMP())
      AND CREATED_BY = 'SYSTEM_AUTO_SYNC'
) s ON t.EXTRACT_ID = s.EXTRACT_ID
WHEN MATCHED AND t.SYNC_TO_PHASE2_AT IS NULL THEN
    UPDATE SET 
        SYNC_TO_PHASE2_AT = CURRENT_TIMESTAMP(),
        PROCESSING_STATUS = 'SYNCED_TO_PHASE2',
        UPDATED_AT = CURRENT_TIMESTAMP(),
        UPDATED_BY = 'SYSTEM_AUTO_UPDATE';

-- TASK 5: Update Phase 2 sync status
CREATE OR REPLACE TASK LOGISTICS_DB.COMMON.UPDATE_PHASE2_SYNC_STATUS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
AS
MERGE INTO LOGISTICS_DB.PHASE2_SCHEMA.GATE_TRANSACTIONS t
USING (
    SELECT DISTINCT TRANSACTION_ID
    FROM LOGISTICS_DB.PHASE3_SCHEMA.WAREHOUSE_INVENTORY
    WHERE CREATED_AT >= DATEADD(MINUTE, -10, CURRENT_TIMESTAMP())
      AND CREATED_BY = 'SYSTEM_AUTO_SYNC'
) s ON t.TRANSACTION_ID = s.TRANSACTION_ID
WHEN MATCHED AND t.SYNC_TO_PHASE3_AT IS NULL THEN
    UPDATE SET 
        SYNC_TO_PHASE3_AT = CURRENT_TIMESTAMP(),
        PROCESSING_STATUS = 'SYNCED_TO_PHASE3',
        UPDATED_AT = CURRENT_TIMESTAMP(),
        UPDATED_BY = 'SYSTEM_AUTO_UPDATE';

-- TASK 6: Update Phase 3 sync status
CREATE OR REPLACE TASK LOGISTICS_DB.COMMON.UPDATE_PHASE3_SYNC_STATUS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
AS
MERGE INTO LOGISTICS_DB.PHASE3_SCHEMA.WAREHOUSE_INVENTORY t
USING (
    SELECT DISTINCT INVENTORY_ID
    FROM LOGISTICS_DB.PHASE4_SCHEMA.SAP_INTEGRATION
    WHERE CREATED_AT >= DATEADD(MINUTE, -10, CURRENT_TIMESTAMP())
      AND CREATED_BY = 'SYSTEM_AUTO_SYNC'
) s ON t.INVENTORY_ID = s.INVENTORY_ID
WHEN MATCHED AND t.SYNC_TO_PHASE4_AT IS NULL THEN
    UPDATE SET 
        SYNC_TO_PHASE4_AT = CURRENT_TIMESTAMP(),
        PROCESSING_STATUS = 'SYNCED_TO_PHASE4',
        STOCK_STATUS = 'SYNCED_TO_PHASE4',
        UPDATED_AT = CURRENT_TIMESTAMP(),
        UPDATED_BY = 'SYSTEM_AUTO_UPDATE';

-- =====================================================
-- STEP 5: CREATE MONITORING VIEWS
-- =====================================================

-- Comprehensive pipeline monitoring view
CREATE OR REPLACE VIEW LOGISTICS_DB.COMMON.V_PIPELINE_MONITORING AS
SELECT 
    p1.BL_NUMBER, p1.CONTAINER_NUMBER, p1.EXTRACT_ID,
    
    -- Phase 1 Status
    p1.PROCESSING_STATUS AS PHASE1_STATUS,
    p1.REVIEW_STATUS AS PHASE1_REVIEW,
    p1.CONFIDENCE_SCORE AS PHASE1_AI_CONFIDENCE,
    p1.CREATED_AT AS PHASE1_CREATED_AT,
    p1.SYNC_TO_PHASE2_AT AS PHASE1_SYNCED_AT,
    
    -- Phase 2 Status
    p2.TRANSACTION_ID,
    p2.PROCESSING_STATUS AS PHASE2_STATUS,
    p2.GATE_IN_TIME AS PHASE2_GATE_IN,
    p2.ASSIGNED_LOCATION AS PHASE2_LOCATION,
    p2.SYNC_TO_PHASE3_AT AS PHASE2_SYNCED_AT,
    
    -- Phase 3 Status
    p3.INVENTORY_ID,
    p3.PROCESSING_STATUS AS PHASE3_STATUS,
    p3.WAREHOUSE_CODE AS PHASE3_WAREHOUSE,
    p3.STOCK_STATUS AS PHASE3_STOCK_STATUS,
    p3.SYNC_TO_PHASE4_AT AS PHASE3_SYNCED_AT,
    
    -- Phase 4 Status
    p4.SAP_INTEGRATION_ID,
    p4.SAP_SYNC_STATUS AS PHASE4_SAP_STATUS,
    p4.SAP_INVOICE_NUMBER AS PHASE4_INVOICE,
    p4.FULLY_INTEGRATED AS PHASE4_COMPLETE,
    p4.LAST_SYNC_SUCCESS_AT AS PHASE4_SAP_SYNCED_AT,
    
    -- Overall Pipeline Health
    CASE 
        WHEN p4.FULLY_INTEGRATED = TRUE THEN 'COMPLETED'
        WHEN p4.SAP_INTEGRATION_ID IS NOT NULL THEN 'IN_PHASE4'
        WHEN p3.INVENTORY_ID IS NOT NULL THEN 'IN_PHASE3'
        WHEN p2.TRANSACTION_ID IS NOT NULL THEN 'IN_PHASE2'
        WHEN p1.EXTRACT_ID IS NOT NULL THEN 'IN_PHASE1'
        ELSE 'UNKNOWN'
    END AS PIPELINE_STAGE,
    
    DATEDIFF(HOUR, p1.CREATED_AT, 
        COALESCE(p4.LAST_SYNC_SUCCESS_AT, p3.SYNC_TO_PHASE4_AT, 
                 p2.SYNC_TO_PHASE3_AT, CURRENT_TIMESTAMP())
    ) AS TOTAL_PROCESSING_HOURS,
    
    -- Bottleneck Detection
    CASE 
        WHEN p1.NEEDS_HUMAN_REVIEW = TRUE AND p1.REVIEW_STATUS = 'PENDING' 
            THEN 'STUCK_AT_REVIEW'
        WHEN p1.REVIEW_STATUS = 'APPROVED' AND p2.TRANSACTION_ID IS NULL 
             AND DATEDIFF(HOUR, p1.REVIEWED_AT, CURRENT_TIMESTAMP()) > 2 
            THEN 'PHASE1_TO_PHASE2_DELAY'
        WHEN p2.GATE_IN_TIME IS NOT NULL AND p3.INVENTORY_ID IS NULL 
             AND DATEDIFF(HOUR, p2.GATE_IN_TIME, CURRENT_TIMESTAMP()) > 1 
            THEN 'PHASE2_TO_PHASE3_DELAY'
        WHEN p3.STOCK_STATUS = 'IN_STOCK' AND p4.SAP_INTEGRATION_ID IS NULL 
             AND DATEDIFF(HOUR, p3.STOCK_IN_DATE, CURRENT_TIMESTAMP()) > 4 
            THEN 'PHASE3_TO_PHASE4_DELAY'
        WHEN p4.SAP_SYNC_STATUS = 'FAILED' 
            THEN 'SAP_SYNC_FAILED'
        ELSE 'ON_TRACK'
    END AS BOTTLENECK_FLAG
FROM LOGISTICS_DB.PHASE1_SCHEMA.BL_EXTRACTS p1
LEFT JOIN LOGISTICS_DB.PHASE2_SCHEMA.GATE_TRANSACTIONS p2 
    ON p1.EXTRACT_ID = p2.EXTRACT_ID
LEFT JOIN LOGISTICS_DB.PHASE3_SCHEMA.WAREHOUSE_INVENTORY p3 
    ON p2.TRANSACTION_ID = p3.TRANSACTION_ID
LEFT JOIN LOGISTICS_DB.PHASE4_SCHEMA.SAP_INTEGRATION p4 
    ON p3.INVENTORY_ID = p4.INVENTORY_ID;

-- Executive Dashboard with KPIs
CREATE OR REPLACE VIEW LOGISTICS_DB.COMMON.V_EXECUTIVE_DASHBOARD AS
SELECT 
    CURRENT_DATE() AS REPORT_DATE,
    
    -- Phase 1 Metrics
    COUNT(DISTINCT p1.EXTRACT_ID) AS TOTAL_BL_EXTRACTED,
    SUM(CASE WHEN p1.CONFIDENCE_SCORE >= 85 THEN 1 ELSE 0 END) AS AUTO_APPROVED_COUNT,
    SUM(CASE WHEN p1.NEEDS_HUMAN_REVIEW = TRUE THEN 1 ELSE 0 END) AS HUMAN_REVIEW_COUNT,
    ROUND(AVG(p1.CONFIDENCE_SCORE), 2) AS AVG_AI_CONFIDENCE,
    
    -- Phase 2 Metrics
    COUNT(DISTINCT p2.TRANSACTION_ID) AS TOTAL_GATE_TRANSACTIONS,
    SUM(CASE WHEN p2.TRANSACTION_TYPE = 'GATE_IN' THEN 1 ELSE 0 END) AS GATE_IN_COUNT,
    SUM(CASE WHEN p2.TRANSACTION_TYPE = 'GATE_OUT' THEN 1 ELSE 0 END) AS GATE_OUT_COUNT,
    ROUND(AVG(p2.DURATION_MINUTES), 2) AS AVG_GATE_DURATION_MIN,
    
    -- Phase 3 Metrics
    COUNT(DISTINCT p3.INVENTORY_ID) AS TOTAL_INVENTORY_ITEMS,
    COUNT(DISTINCT p3.WAREHOUSE_CODE) AS ACTIVE_WAREHOUSES,
    SUM(CASE WHEN p3.STOCK_STATUS = 'IN_STOCK' THEN 1 ELSE 0 END) AS CURRENT_STOCK_COUNT,
    SUM(p3.RESTACKING_COUNT) AS TOTAL_RESTACKING_OPERATIONS,
    
    -- Phase 4 Metrics
    COUNT(DISTINCT p4.SAP_INTEGRATION_ID) AS TOTAL_SAP_RECORDS,
    SUM(CASE WHEN p4.SAP_SYNC_STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SAP_SUCCESS_COUNT,
    SUM(CASE WHEN p4.SAP_SYNC_STATUS = 'FAILED' THEN 1 ELSE 0 END) AS SAP_FAILED_COUNT,
    SUM(CASE WHEN p4.FULLY_INTEGRATED = TRUE THEN 1 ELSE 0 END) AS FULLY_INTEGRATED_COUNT,
    ROUND(SUM(p4.INVOICE_AMOUNT), 2) AS TOTAL_INVOICE_AMOUNT_VND,
    
    -- Overall Pipeline Health
    ROUND(
        SUM(CASE WHEN p4.FULLY_INTEGRATED = TRUE THEN 1 ELSE 0 END) * 100.0 / 
        NULLIF(COUNT(DISTINCT p1.EXTRACT_ID), 0), 
    2) AS END_TO_END_COMPLETION_RATE,
    
    -- Business Value Metrics
    ROUND(COUNT(DISTINCT p1.EXTRACT_ID) * 45 / 60.0, 2) AS MANUAL_HOURS_SAVED,
    ROUND((COUNT(DISTINCT p2.TRANSACTION_ID) * 13500000000.0 / 365 / 3000), 0) AS ANONYMOUS_PORTAL_SAVINGS_VND
FROM LOGISTICS_DB.PHASE1_SCHEMA.BL_EXTRACTS p1
LEFT JOIN LOGISTICS_DB.PHASE2_SCHEMA.GATE_TRANSACTIONS p2 
    ON p1.EXTRACT_ID = p2.EXTRACT_ID
LEFT JOIN LOGISTICS_DB.PHASE3_SCHEMA.WAREHOUSE_INVENTORY p3 
    ON p2.TRANSACTION_ID = p3.TRANSACTION_ID
LEFT JOIN LOGISTICS_DB.PHASE4_SCHEMA.SAP_INTEGRATION p4 
    ON p3.INVENTORY_ID = p4.INVENTORY_ID
WHERE p1.CREATED_AT >= DATEADD(DAY, -30, CURRENT_DATE());

-- =====================================================
-- STEP 6: ACTIVATE TASKS
-- =====================================================
ALTER TASK LOGISTICS_DB.COMMON.SYNC_PHASE1_TO_PHASE2 RESUME;
ALTER TASK LOGISTICS_DB.COMMON.SYNC_PHASE2_TO_PHASE3 RESUME;
ALTER TASK LOGISTICS_DB.COMMON.SYNC_PHASE3_TO_PHASE4 RESUME;
ALTER TASK LOGISTICS_DB.COMMON.UPDATE_PHASE1_SYNC_STATUS RESUME;
ALTER TASK LOGISTICS_DB.COMMON.UPDATE_PHASE2_SYNC_STATUS RESUME;
ALTER TASK LOGISTICS_DB.COMMON.UPDATE_PHASE3_SYNC_STATUS RESUME;

-- =====================================================
-- STEP 7: INSERT SAMPLE DATA (Optional - for testing)
-- =====================================================
INSERT INTO LOGISTICS_DB.PHASE1_SCHEMA.BL_EXTRACTS (
    EXTRACT_ID, BL_NUMBER, PDF_FILE_NAME, CONTAINER_NUMBER,
    SHIPPER_NAME, CONSIGNEE_NAME, VESSEL_NAME, VOYAGE_NUMBER,
    PORT_OF_LOADING, PORT_OF_DISCHARGE, ETD, ETA,
    CARGO_DESCRIPTION, GROSS_WEIGHT, CONFIDENCE_SCORE,
    NEEDS_HUMAN_REVIEW, REVIEW_STATUS, PROCESSING_STATUS, CREATED_BY
)
SELECT 
    'EXT-2026-' || LPAD(SEQ4()::VARCHAR, 6, '0'),
    'BL20260623' || LPAD(SEQ4()::VARCHAR, 5, '0'),
    'BL_' || LPAD(SEQ4()::VARCHAR, 5, '0') || '.pdf',
    'CONT' || LPAD((SEQ4() + 1000)::VARCHAR, 7, '0'),
    'ACME Shipping Co. Ltd.',
    'Vietnam Logistics Services JSC',
    CASE SEQ4() % 3 
        WHEN 0 THEN 'MAERSK SEALAND'
        WHEN 1 THEN 'COSCO SHIPPING'
        ELSE 'EVERGREEN MARINE'
    END,
    'VOY-' || LPAD(SEQ4()::VARCHAR, 3, '0'),
    CASE SEQ4() % 3
        WHEN 0 THEN 'SHANGHAI, CHINA'
        WHEN 1 THEN 'SINGAPORE'
        ELSE 'HONG KONG'
    END,
    'HO CHI MINH, VIETNAM',
    DATEADD(DAY, SEQ4(), CURRENT_DATE()),
    DATEADD(DAY, SEQ4() + 7, CURRENT_DATE()),
    'GENERAL CARGO - ELECTRONICS',
    15000 + (SEQ4() * 100),
    CASE WHEN SEQ4() % 5 = 0 THEN 75.5 ELSE 92.3 END,
    CASE WHEN SEQ4() % 5 = 0 THEN TRUE ELSE FALSE END,
    CASE WHEN SEQ4() % 5 = 0 THEN 'PENDING' ELSE 'APPROVED' END,
    CASE WHEN SEQ4() % 5 = 0 THEN 'EXTRACTED' ELSE 'REVIEWED' END,
    'SYSTEM_SAMPLE_DATA'
FROM TABLE(GENERATOR(ROWCOUNT => 10));

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================

-- Check sample data in Phase 1
SELECT 
    EXTRACT_ID, BL_NUMBER, CONTAINER_NUMBER, VESSEL_NAME,
    REVIEW_STATUS, PROCESSING_STATUS, CONFIDENCE_SCORE
FROM LOGISTICS_DB.PHASE1_SCHEMA.BL_EXTRACTS
ORDER BY CREATED_AT DESC LIMIT 10;

-- Check task status
SHOW TASKS IN SCHEMA LOGISTICS_DB.COMMON;

-- View executive dashboard
SELECT * FROM LOGISTICS_DB.COMMON.V_EXECUTIVE_DASHBOARD;

-- View pipeline monitoring
SELECT * FROM LOGISTICS_DB.COMMON.V_PIPELINE_MONITORING
ORDER BY PHASE1_CREATED_AT DESC LIMIT 10;

-- =====================================================
-- END OF SETUP SCRIPT
-- =====================================================
-- Next steps:
-- 1. Wait 5 minutes for first task execution
-- 2. Check V_PIPELINE_MONITORING to see data flowing
-- 3. Integrate with Mendix apps for Phase 1, 2, 3, 4
-- =====================================================
