-- ============================================
-- VF LOGISTICS - DATABASE BACKUP SCRIPT
-- Generated: 2026-07-04
-- Account: JMAXFXA-XN12202
-- Database: MENDIX_APP
-- Schema: AGENTS
-- ============================================

-- This script exports DDL for all Snowflake objects
-- Run each section to get DDL output

USE DATABASE MENDIX_APP;
USE SCHEMA AGENTS;

-- ============================================
-- SECTION 1: TABLES DDL
-- ============================================

SELECT '-- TABLE: AI_ANOMALY_REPORT' as OBJECT_TYPE, GET_DDL('TABLE', 'MENDIX_APP.AGENTS.AI_ANOMALY_REPORT') as DDL
UNION ALL
SELECT '-- TABLE: AI_CALL_LOG', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.AI_CALL_LOG')
UNION ALL
SELECT '-- TABLE: AI_CLASSIFICATION_CACHE', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.AI_CLASSIFICATION_CACHE')
UNION ALL
SELECT '-- TABLE: ANALYTICS_AI_DAILY_REPORT', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.ANALYTICS_AI_DAILY_REPORT')
UNION ALL
SELECT '-- TABLE: ANALYTICS_CARRIER_PERFORMANCE', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.ANALYTICS_CARRIER_PERFORMANCE')
UNION ALL
SELECT '-- TABLE: ANALYTICS_ROUTE_SUMMARY', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.ANALYTICS_ROUTE_SUMMARY')
UNION ALL
SELECT '-- TABLE: APP_CONFIG', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.APP_CONFIG')
UNION ALL
SELECT '-- TABLE: BILL_OF_LADING', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.BILL_OF_LADING')
UNION ALL
SELECT '-- TABLE: CHAT_SESSION', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.CHAT_SESSION')
UNION ALL
SELECT '-- TABLE: COMPLIANCE_CHECK_RESULT', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.COMPLIANCE_CHECK_RESULT')
UNION ALL
SELECT '-- TABLE: CONTAINER_PHOTO_VERIFICATION', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.CONTAINER_PHOTO_VERIFICATION')
UNION ALL
SELECT '-- TABLE: DOCUMENT_DISCREPANCY', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.DOCUMENT_DISCREPANCY')
UNION ALL
SELECT '-- TABLE: FRAUD_ALERT', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.FRAUD_ALERT')
UNION ALL
SELECT '-- TABLE: HS_CODE_REFERENCE', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.HS_CODE_REFERENCE')
UNION ALL
SELECT '-- TABLE: PORT_MASTER', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.PORT_MASTER')
UNION ALL
SELECT '-- TABLE: SAP_CO_COST_ALLOCATION', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.SAP_CO_COST_ALLOCATION')
UNION ALL
SELECT '-- TABLE: SAP_FI_DOCUMENT', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.SAP_FI_DOCUMENT')
UNION ALL
SELECT '-- TABLE: SAP_FI_LINE_ITEM', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.SAP_FI_LINE_ITEM')
UNION ALL
SELECT '-- TABLE: SAP_MM_GOODS_RECEIPT', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.SAP_MM_GOODS_RECEIPT')
UNION ALL
SELECT '-- TABLE: SAP_SD_DELIVERY', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.SAP_SD_DELIVERY')
UNION ALL
SELECT '-- TABLE: VESSEL_REGISTRY', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.VESSEL_REGISTRY');

-- ============================================
-- SECTION 2: DYNAMIC TABLES DDL
-- ============================================

SELECT '-- DYNAMIC TABLE: DT_SHIPMENT_KPI' as OBJECT_TYPE, GET_DDL('TABLE', 'MENDIX_APP.AGENTS.DT_SHIPMENT_KPI') as DDL
UNION ALL
SELECT '-- DYNAMIC TABLE: DT_CARRIER_PERFORMANCE', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.DT_CARRIER_PERFORMANCE')
UNION ALL
SELECT '-- DYNAMIC TABLE: DT_ROUTE_ANALYTICS', GET_DDL('TABLE', 'MENDIX_APP.AGENTS.DT_ROUTE_ANALYTICS');

-- ============================================
-- SECTION 3: STORED PROCEDURES DDL
-- ============================================

SELECT PROCEDURE_NAME, GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.' || PROCEDURE_NAME) as DDL
FROM INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'AGENTS'
ORDER BY PROCEDURE_NAME;

-- ============================================
-- SECTION 4: FUNCTIONS DDL
-- ============================================

SELECT FUNCTION_NAME, GET_DDL('FUNCTION', 'MENDIX_APP.AGENTS.' || FUNCTION_NAME) as DDL
FROM INFORMATION_SCHEMA.FUNCTIONS
WHERE FUNCTION_SCHEMA = 'AGENTS'
ORDER BY FUNCTION_NAME;

-- ============================================
-- SECTION 5: TASKS DDL
-- ============================================

SELECT NAME as TASK_NAME, GET_DDL('TASK', 'MENDIX_APP.AGENTS.' || NAME) as DDL
FROM INFORMATION_SCHEMA.TASKS
WHERE SCHEMA_NAME = 'AGENTS'
ORDER BY NAME;

-- ============================================
-- SECTION 6: DATA EXPORT (Reference Tables)
-- ============================================

-- PORT_MASTER
SELECT 'INSERT INTO PORT_MASTER VALUES (' ||
    '''' || PORT_CODE || ''', ' ||
    '''' || PORT_NAME || ''', ' ||
    '''' || COUNTRY_CODE || ''', ' ||
    '''' || REPLACE(PORT_NAME_LOCAL, '''', '''''') || ''', ' ||
    CASE WHEN IS_MAJOR_PORT THEN 'TRUE' ELSE 'FALSE' END || ', ' ||
    CASE WHEN IS_SANCTIONED THEN 'TRUE' ELSE 'FALSE' END ||
    ');' as INSERT_STATEMENT
FROM PORT_MASTER
LIMIT 1000;

-- HS_CODE_REFERENCE
SELECT 'INSERT INTO HS_CODE_REFERENCE VALUES (' ||
    '''' || HS_CODE || ''', ' ||
    '''' || REPLACE(DESCRIPTION, '''', '''''') || ''', ' ||
    '''' || CATEGORY || ''', ' ||
    CASE WHEN IS_DANGEROUS_GOODS THEN 'TRUE' ELSE 'FALSE' END || ', ' ||
    CASE WHEN IS_RESTRICTED THEN 'TRUE' ELSE 'FALSE' END ||
    ');' as INSERT_STATEMENT
FROM HS_CODE_REFERENCE
LIMIT 1000;

-- VESSEL_REGISTRY
SELECT 'INSERT INTO VESSEL_REGISTRY VALUES (' ||
    VESSEL_ID || ', ' ||
    '''' || VESSEL_NAME || ''', ' ||
    '''' || IMO_NUMBER || ''', ' ||
    '''' || FLAG || ''', ' ||
    GROSS_TONNAGE || ', ' ||
    BUILT_YEAR ||
    ');' as INSERT_STATEMENT
FROM VESSEL_REGISTRY
LIMIT 1000;

-- ============================================
-- SECTION 7: DATA EXPORT (Operational Tables - Sample)
-- ============================================

-- BILL_OF_LADING (10,010 records - full export)
SELECT 'INSERT INTO BILL_OF_LADING (BL_ID, BL_NUMBER, SHIPPER_NAME, CONSIGNEE_NAME, CONTAINER_NUMBER, STATUS) VALUES (' ||
    BL_ID || ', ' ||
    '''' || BL_NUMBER || ''', ' ||
    '''' || REPLACE(SHIPPER_NAME, '''', '''''') || ''', ' ||
    '''' || REPLACE(CONSIGNEE_NAME, '''', '''''') || ''', ' ||
    '''' || CONTAINER_NUMBER || ''', ' ||
    '''' || STATUS || ''' ' ||
    ');' as INSERT_STATEMENT
FROM BILL_OF_LADING
LIMIT 10010;

-- AI_CALL_LOG (sample 500 records)
SELECT 'INSERT INTO AI_CALL_LOG (CALL_ID, MODEL_NAME, CALL_STATUS, TOTAL_TOKENS) VALUES (' ||
    CALL_ID || ', ' ||
    '''' || MODEL_NAME || ''', ' ||
    '''' || CALL_STATUS || ''', ' ||
    TOTAL_TOKENS ||
    ');' as INSERT_STATEMENT
FROM AI_CALL_LOG
ORDER BY CALL_TIMESTAMP DESC
LIMIT 500;

-- FRAUD_ALERT (all open alerts)
SELECT 'INSERT INTO FRAUD_ALERT (ALERT_ID, ALERT_TYPE, SEVERITY, DESCRIPTION, STATUS) VALUES (' ||
    ALERT_ID || ', ' ||
    '''' || ALERT_TYPE || ''', ' ||
    '''' || SEVERITY || ''', ' ||
    '''' || REPLACE(DESCRIPTION, '''', '''''') || ''', ' ||
    '''' || STATUS || ''' ' ||
    ');' as INSERT_STATEMENT
FROM FRAUD_ALERT
LIMIT 1000;
