-- ============================================================================
-- VF LOGISTICS AI-POWERED ENTERPRISE SEAPORT PLATFORM
-- Master Deployment Script — Full reproducible setup
-- Team SORA | Snowflake CoCo CLI Hackathon 2026 | Track 1: Workflow Automation
-- ============================================================================
-- USAGE: Execute this script top-to-bottom in Snowflake Worksheets or via Snow CLI
-- PREREQUISITES: ACCOUNTADMIN role, trial account with Cortex AI access
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================================
-- STEP 1: DATABASE + SCHEMA SETUP
-- ============================================================================
CREATE DATABASE IF NOT EXISTS MENDIX_APP;
CREATE SCHEMA IF NOT EXISTS MENDIX_APP.AGENTS;
USE SCHEMA MENDIX_APP.AGENTS;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 120 AUTO_RESUME = TRUE;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================================
-- STEP 2: CORE TABLES (20 tables)
-- ============================================================================

-- Bill of Lading (main operational table — 10,010 records)
CREATE TABLE IF NOT EXISTS BILL_OF_LADING (
    BL_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    BL_NUMBER VARCHAR(50),
    CARRIER_NAME VARCHAR(100),
    VESSEL_NAME VARCHAR(100),
    IMO_NUMBER VARCHAR(20),
    VOYAGE_NUMBER VARCHAR(30),
    PORT_OF_LOADING VARCHAR(100),
    PORT_OF_LOADING_LOCODE VARCHAR(10),
    PORT_OF_DISCHARGE VARCHAR(100),
    PORT_OF_DISCHARGE_LOCODE VARCHAR(10),
    ETD DATE,
    ETA DATE,
    CONTAINER_NUMBER VARCHAR(20),
    CONTAINER_TYPE VARCHAR(20),
    CONTAINER_TARE_KGS NUMBER,
    SEAL_NUMBER_SHIPPER VARCHAR(30),
    SEAL_NUMBER_CARRIER VARCHAR(30),
    COMMODITY_DESCRIPTION VARCHAR(500),
    HS_CODE VARCHAR(20),
    GROSS_WEIGHT_KGS NUMBER(12,2),
    VGM_WEIGHT_KGS NUMBER(12,2),
    NUMBER_OF_PACKAGES NUMBER,
    MEASUREMENT_CBM NUMBER(10,3),
    TOTAL_CHARGES NUMBER(12,2),
    OCEAN_FREIGHT NUMBER(10,2),
    THC_ORIGIN NUMBER(10,2),
    THC_DESTINATION NUMBER(10,2),
    DOCUMENTATION_FEE NUMBER(10,2),
    SEAL_FEE NUMBER(10,2),
    BAF NUMBER(10,2),
    INCOTERMS VARCHAR(10),
    SHIPPER_COMPANY VARCHAR(200),
    CONSIGNEE_COMPANY VARCHAR(200),
    NOTIFY_PARTY VARCHAR(200),
    STATUS VARCHAR(30) DEFAULT 'DRAFT',
    AI_DOCUMENT_TYPE VARCHAR(50),
    AI_CONFIDENCE_SCORE NUMBER(5,3),
    SYNCED_TO_ERP BOOLEAN DEFAULT FALSE,
    ERP_SYNC_DATE TIMESTAMP,
    PROCESSED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Reference Tables
CREATE TABLE IF NOT EXISTS PORT_MASTER (
    PORT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PORT_CODE VARCHAR(10) UNIQUE,
    PORT_NAME VARCHAR(100),
    COUNTRY VARCHAR(50),
    COUNTRY_CODE VARCHAR(5),
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6),
    TIMEZONE VARCHAR(50),
    PORT_TYPE VARCHAR(20),
    MAX_DRAFT_M NUMBER(5,2),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS VESSEL_REGISTRY (
    VESSEL_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    IMO_NUMBER VARCHAR(20) UNIQUE,
    VESSEL_NAME VARCHAR(100),
    FLAG VARCHAR(50),
    VESSEL_TYPE VARCHAR(50),
    GROSS_TONNAGE NUMBER,
    NET_TONNAGE NUMBER,
    TEU_CAPACITY NUMBER,
    OPERATOR VARCHAR(100),
    YEAR_BUILT NUMBER,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS HS_CODE_REFERENCE (
    HS_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    HS_CODE VARCHAR(20),
    DESCRIPTION VARCHAR(300),
    CHAPTER VARCHAR(100),
    IS_DANGEROUS_GOODS BOOLEAN DEFAULT FALSE,
    DG_CLASS VARCHAR(10),
    TYPICAL_WEIGHT_PER_CBM NUMBER(10,2),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- AI & Audit Tables
CREATE TABLE IF NOT EXISTS AI_CALL_LOG (
    LOG_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    CALL_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PROCEDURE_NAME VARCHAR(100),
    AI_FUNCTION VARCHAR(50),
    MODEL_NAME VARCHAR(50),
    INPUT_TOKENS NUMBER,
    OUTPUT_TOKENS NUMBER,
    TOTAL_TOKENS NUMBER,
    LATENCY_MS NUMBER,
    STATUS VARCHAR(30),
    ERROR_MESSAGE VARCHAR(1000),
    SESSION_ID VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS AI_CLASSIFICATION_CACHE (
    CACHE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    INPUT_HASH VARCHAR(32),
    DOCUMENT_TYPE VARCHAR(50),
    CONFIDENCE NUMBER(5,3),
    REASONING VARCHAR(500),
    CACHED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CHAT_SESSION (
    MESSAGE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SESSION_ID VARCHAR(100),
    USER_ID VARCHAR(100),
    ROLE VARCHAR(20),
    CONTENT VARCHAR(5000),
    TOKENS_USED NUMBER,
    LATENCY_MS NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FRAUD_ALERT (
    ALERT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ALERT_TYPE VARCHAR(50),
    SEVERITY VARCHAR(20),
    DESCRIPTION VARCHAR(500),
    DOCUMENT_IDS VARCHAR(200),
    STATUS VARCHAR(20) DEFAULT 'OPEN',
    RESOLVED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- SAP Integration Tables
CREATE TABLE IF NOT EXISTS SAP_FI_DOCUMENT (
    FI_DOC_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_CODE VARCHAR(10),
    FISCAL_YEAR NUMBER,
    POSTING_DATE DATE,
    DOCUMENT_DATE DATE,
    DOC_TYPE VARCHAR(5),
    CURRENCY VARCHAR(5),
    TOTAL_AMOUNT NUMBER(12,2),
    VENDOR_CODE VARCHAR(20),
    VENDOR_NAME VARCHAR(100),
    GL_ACCOUNT VARCHAR(20),
    COST_CENTER VARCHAR(20),
    REFERENCE VARCHAR(50),
    STATUS VARCHAR(20),
    BL_ID_REF NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SAP_FI_LINE_ITEM (
    LINE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    FI_DOC_ID NUMBER,
    LINE_NUMBER NUMBER,
    GL_ACCOUNT VARCHAR(20),
    DEBIT_CREDIT VARCHAR(1),
    AMOUNT NUMBER(12,2),
    COST_CENTER VARCHAR(20),
    TAX_CODE VARCHAR(5),
    DESCRIPTION VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS SAP_MM_GOODS_RECEIPT (
    GR_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    MAT_DOC_NUMBER VARCHAR(20),
    MOVEMENT_TYPE VARCHAR(5),
    POSTING_DATE DATE,
    PLANT VARCHAR(10),
    STORAGE_LOCATION VARCHAR(10),
    MATERIAL_NUMBER VARCHAR(20),
    MATERIAL_DESC VARCHAR(200),
    QUANTITY NUMBER(12,2),
    UOM VARCHAR(10),
    PO_NUMBER VARCHAR(20),
    CONTAINER_NUMBER VARCHAR(20),
    BL_REFERENCE VARCHAR(50),
    STATUS VARCHAR(20),
    BL_ID_REF NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SAP_SD_DELIVERY (
    SD_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    DELIVERY_NUMBER VARCHAR(20),
    DELIVERY_TYPE VARCHAR(5),
    SHIP_TO_PARTY VARCHAR(20),
    SHIP_TO_NAME VARCHAR(100),
    SHIPPING_POINT VARCHAR(10),
    ROUTE VARCHAR(20),
    PLANNED_GI_DATE DATE,
    ACTUAL_GI_DATE DATE,
    BILLING_DOC VARCHAR(20),
    BILLING_AMOUNT NUMBER(12,2),
    BILLING_CURRENCY VARCHAR(5),
    BILLING_DATE DATE,
    SALES_ORDER VARCHAR(20),
    INCOTERMS VARCHAR(10),
    BL_REFERENCE VARCHAR(50),
    STATUS VARCHAR(20),
    BL_ID_REF NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SAP_CO_COST_ALLOCATION (
    CO_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    COST_CENTER VARCHAR(20),
    COST_ELEMENT VARCHAR(20),
    COST_ELEMENT_DESC VARCHAR(100),
    AMOUNT NUMBER(12,2),
    CURRENCY VARCHAR(5),
    PERIOD NUMBER,
    FISCAL_YEAR NUMBER,
    COST_TYPE VARCHAR(30),
    BL_REFERENCE VARCHAR(50),
    BL_ID_REF NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Compliance & Verification
CREATE TABLE IF NOT EXISTS COMPLIANCE_CHECK_RESULT (
    CHECK_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    BL_ID NUMBER,
    CHECK_TYPE VARCHAR(50),
    STATUS VARCHAR(20),
    DETAILS VARIANT,
    CHECKED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTAINER_PHOTO_VERIFICATION (
    VERIFY_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    BL_NUMBER VARCHAR(50),
    PHOTO_PATH VARCHAR(500),
    DETECTED_CONTAINER_NO VARCHAR(20),
    EXPECTED_CONTAINER_NO VARCHAR(20),
    CONTAINER_MATCH BOOLEAN,
    DETECTED_SEAL_NO VARCHAR(30),
    EXPECTED_SEAL_NO VARCHAR(30),
    SEAL_MATCH BOOLEAN,
    CONDITION_ASSESSMENT VARCHAR(20),
    CONDITION_DETAILS VARCHAR(500),
    AI_CONFIDENCE FLOAT,
    VERIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DOCUMENT_DISCREPANCY (
    DISCREPANCY_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SOURCE_DOC_ID NUMBER,
    TARGET_DOC_ID NUMBER,
    FIELD_NAME VARCHAR(50),
    SOURCE_VALUE VARCHAR(200),
    TARGET_VALUE VARCHAR(200),
    SEVERITY VARCHAR(20),
    METHOD VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Analytics (refreshed by RUN_ANALYTICS_PIPELINE)
CREATE TABLE IF NOT EXISTS ANALYTICS_ROUTE_SUMMARY (
    COUNTRY VARCHAR(50),
    SHIPMENT_COUNT NUMBER,
    AVG_WEIGHT_KG FLOAT,
    TOTAL_REVENUE FLOAT
);

CREATE TABLE IF NOT EXISTS ANALYTICS_CARRIER_PERFORMANCE (
    CARRIER_NAME VARCHAR(100),
    TOTAL_SHIPMENTS NUMBER,
    AVG_WEIGHT FLOAT,
    TOTAL_REVENUE FLOAT
);

CREATE TABLE IF NOT EXISTS ANALYTICS_AI_DAILY_REPORT (
    CALL_DATE DATE,
    PROCEDURE_NAME VARCHAR(100),
    TOTAL_CALLS NUMBER,
    TOTAL_TOKENS NUMBER,
    AVG_LATENCY_MS FLOAT
);

-- System Configuration (runtime parameters)
CREATE TABLE IF NOT EXISTS APP_CONFIG (
    CONFIG_KEY VARCHAR(50) PRIMARY KEY,
    CONFIG_VALUE VARCHAR(200),
    DESCRIPTION VARCHAR(300),
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Insert default config
MERGE INTO APP_CONFIG t USING (
    SELECT 'AI_MODEL' as K, 'llama3-8b' as V, 'Primary LLM model for AI functions' as D
    UNION ALL SELECT 'FRAUD_CONFIDENCE_THRESHOLD', '85', 'Minimum confidence % to flag fraud'
    UNION ALL SELECT 'DAILY_COST_ALERT_USD', '0.005', 'Daily AI cost alert threshold in USD'
    UNION ALL SELECT 'CACHE_TTL_SECONDS', '600', 'Dashboard cache duration in seconds'
    UNION ALL SELECT 'BULK_SCAN_BATCH_SIZE', '100', 'Max records for bulk scan operations'
) s ON t.CONFIG_KEY = s.K
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES (s.K, s.V, s.D);

-- ============================================================================
-- STEP 3: VIEWS (7 views — Marketplace cross-database)
-- ============================================================================

CREATE OR REPLACE VIEW V_AI_DAILY_COST AS
SELECT DATE_TRUNC('DAY', CALL_TIMESTAMP)::DATE as DAY,
       COUNT(*) as TOTAL_CALLS,
       SUM(TOTAL_TOKENS) as TOTAL_TOKENS,
       SUM(INPUT_TOKENS) as INPUT_TOKENS,
       SUM(OUTPUT_TOKENS) as OUTPUT_TOKENS,
       ROUND(AVG(LATENCY_MS), 0) as AVG_LATENCY_MS,
       ROUND(SUM(TOTAL_TOKENS) * 0.000001, 6) as ESTIMATED_COST_USD,
       SUM(CASE WHEN STATUS LIKE '%FAIL%' THEN 1 ELSE 0 END) as ERRORS
FROM AI_CALL_LOG
GROUP BY DAY ORDER BY DAY DESC;

CREATE OR REPLACE VIEW V_AI_USAGE_SUMMARY AS
SELECT PROCEDURE_NAME,
       COUNT(*) as CALL_COUNT,
       SUM(TOTAL_TOKENS) as TOTAL_TOKENS,
       ROUND(AVG(LATENCY_MS), 0) as AVG_LATENCY_MS,
       SUM(CASE WHEN STATUS LIKE '%SUCCESS%' THEN 1 ELSE 0 END) as SUCCESS_COUNT,
       SUM(CASE WHEN STATUS LIKE '%FAIL%' THEN 1 ELSE 0 END) as ERROR_COUNT,
       ROUND(SUM(CASE WHEN STATUS LIKE '%FAIL%' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 1) as ERROR_RATE_PCT
FROM AI_CALL_LOG
GROUP BY PROCEDURE_NAME;

-- NOTE: These views require Marketplace databases. Install them first:
-- 1. GLOBAL_WEATHER__CLIMATE_DATA_BY_PELMOREX_WEATHER_SOURCE (free)
-- 2. SNOWFLAKE_PUBLIC_DATA_FREE (free)

CREATE OR REPLACE VIEW V_EXCHANGE_RATES AS
SELECT VARIABLE as QUOTE_CURRENCY_ID,
       VALUE as EXCHANGE_RATE,
       DATE as RATE_DATE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FX_RATES_TIMESERIES
WHERE VARIABLE IN ('usd_vnd','usd_jpy','usd_eur','usd_cny','usd_krw','usd_sgd','usd_thb','usd_inr','usd_aed','usd_brl','usd_aud','usd_gbp')
QUALIFY ROW_NUMBER() OVER (PARTITION BY VARIABLE ORDER BY DATE DESC) = 1;

CREATE OR REPLACE VIEW V_EXPORT_RESTRICTED_ENTITIES AS
SELECT ENTITY_NAME, ALTERNATE_NAMES, COUNTRY, RESTRICTION_LIST, LISTED_SINCE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.ITA_RESTRICTED_PARTY_LIST;

CREATE OR REPLACE VIEW V_GLOBAL_TRADE_INDEX AS
SELECT REPORTER as COUNTRY, FLOW as DIRECTION, YEAR as PERIOD, VALUE as VALUE_USD
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.WTO_TRADE_VALUE
WHERE REPORTER IN ('Vietnam', 'Japan', 'United States', 'China', 'Germany')
  AND YEAR >= 2020;

CREATE OR REPLACE VIEW V_PORT_WEATHER_FORECAST AS
SELECT p.PORT_CODE, p.PORT_NAME, w.DATE_VALID_STD as FORECAST_DATE,
       w.AVG_TEMPERATURE_AIR_2M_F as TEMP_CELSIUS,
       w.AVG_WIND_SPEED_100M_MPH * 1.609 as WIND_SPEED_KMH,
       CASE 
           WHEN w.AVG_WIND_SPEED_100M_MPH > 40 THEN 'Storm Warning'
           WHEN w.AVG_WIND_SPEED_100M_MPH > 25 THEN 'High Wind'
           WHEN w.TOT_PRECIPITATION_IN > 2 THEN 'Heavy Rain'
           ELSE 'Good Weather'
       END as WEATHER_IMPACT
FROM PORT_MASTER p
CROSS JOIN GLOBAL_WEATHER__CLIMATE_DATA_BY_PELMOREX_WEATHER_SOURCE.STANDARD_TILE.FORECAST_DAY w
WHERE w.POSTAL_CODE IN ('100-0001','90001','10001','20095','3011')
  AND w.DATE_VALID_STD BETWEEN CURRENT_DATE() AND DATEADD(day, 7, CURRENT_DATE());

CREATE OR REPLACE VIEW V_VIETNAM_TRADE_STATS AS
SELECT * FROM V_GLOBAL_TRADE_INDEX WHERE COUNTRY = 'Vietnam';

-- ============================================================================
-- STEP 4: STORED PROCEDURES (22 procedures)
-- NOTE: Full DDL for each procedure is in sql/procedures/ directory
-- Key procedures listed here for reference:
-- ============================================================================
-- AI_COMPLETE_WITH_RETRY(model, prompt, max_retries, caller_proc) → VARIANT
-- CLASSIFY_DOCUMENT_TEXT(doc_text) → VARIANT
-- CLASSIFY_DOCUMENT(file_path) → VARIANT
-- CHECK_COMPLIANCE(doc_id) → VARIANT
-- CROSS_CHECK_DOCUMENTS(source_id, target_id) → VARIANT
-- DETECT_DUPLICATES(doc_id) → VARIANT [NULL=full scan]
-- ENRICH_DOCUMENT(doc_id) → VARIANT
-- SAP_POST_FI_DOCUMENT(bl_id) → VARIANT
-- SAP_POST_GOODS_RECEIPT(bl_id) → VARIANT
-- SAP_CREATE_DELIVERY(bl_id) → VARIANT
-- SAP_ALLOCATE_COSTS(bl_id) → VARIANT
-- SCREEN_SANCTIONS(party_name) → VARIANT
-- GET_EXCHANGE_RATE(from, to, amount) → VARIANT
-- GET_PORT_WEATHER(port_code) → VARIANT
-- GET_TRADE_STATS(country) → VARIANT
-- EXTRACT_FROM_IMAGE(file_path, doc_type) → VARIANT
-- PARSE_XML_EDI(xml_content, message_type) → VARIANT
-- VERIFY_CONTAINER_PHOTO(file_path, bl_number) → VARIANT
-- CHAT_WITH_AGENT(session_id, user_id, message) → VARIANT
-- QUERY_SHIPMENT_STATS(query_type) → VARCHAR
-- QUERY_SHIPMENT_DETAIL(search_type, search_value) → VARCHAR
-- RUN_ANALYTICS_PIPELINE() → VARIANT [Python]

-- ============================================================================
-- STEP 5: FUNCTIONS (8 UDFs)
-- ============================================================================
-- CONVERT_CURRENCY(amount, from_cur, to_cur) → TABLE
-- FN_CALCULATE_DD_FEE(container_number, days_late) → TABLE
-- GET_SHIPMENT_DETAIL(search_type, search_value) → TABLE
-- GET_SHIPMENT_STATS(query_type) → TABLE
-- GET_SHIPMENT_STATS(query_type, filter_value) → TABLE
-- GET_TOKYO_WEATHER_EXTERNAL(days_ahead) → TABLE [Python, External Access]
-- TEST_WEATHER_API() → VARCHAR [Python, External Access]

-- ============================================================================
-- STEP 6: CORTEX SEARCH SERVICE
-- ============================================================================
-- CREATE CORTEX SEARCH SERVICE BL_SEARCH_SERVICE
--   ON CONTENT
--   WAREHOUSE = COMPUTE_WH
--   TARGET_LAG = '5 minutes'
-- AS (
--   SELECT parsed_content:content::STRING AS content, file_path
--   FROM MENDIX_APP.AGENTS.BL_PARSED_DOCUMENTS
-- );

-- ============================================================================
-- STEP 7: CORTEX AGENT
-- ============================================================================
-- CREATE AGENT MENDIX_ASSISTANT
--   COMMENT = 'VF Logistics AI Assistant'
--   TOOLS = (GET_SHIPMENT_STATS, GET_SHIPMENT_DETAIL, BL_SEARCH_SERVICE)
--   MODEL = 'llama3-8b';

-- ============================================================================
-- STEP 8: STREAMLIT DASHBOARD
-- ============================================================================
-- Deploy via Snow CLI:
-- snow stage copy streamlit_app/ @MENDIX_APP.AGENTS.STREAMLIT_STAGE/
-- CREATE STREAMLIT MENDIX_APP.AGENTS.VF_LOGISTICS_DASHBOARD
--   ROOT_LOCATION = '@MENDIX_APP.AGENTS.STREAMLIT_STAGE'
--   MAIN_FILE = 'app.py'
--   QUERY_WAREHOUSE = 'COMPUTE_WH';

-- ============================================================================
-- DEPLOYMENT COMPLETE
-- Objects: 20 tables, 7 views, 22 procedures, 8 functions,
--          1 Cortex Search Service, 1 Cortex Agent, 1 Streamlit App (6 pages)
-- Data: 10,010 B/L records, 70 ports, 20 vessels, 138 HS codes
-- ============================================================================
