-- ============================================================================
-- VF LOGISTICS: ALL STORED PROCEDURES DDL EXPORT
-- Generated from: SELECT GET_DDL('PROCEDURE', ...) for each SP
-- To regenerate: Run sql/export_ddl.sql in Snowflake
-- ============================================================================
-- PROCEDURES INDEX (22 total):
-- 1.  AI_COMPLETE_WITH_RETRY(VARCHAR, VARCHAR, NUMBER, VARCHAR) → VARIANT
-- 2.  CLASSIFY_DOCUMENT_TEXT(VARCHAR) → VARIANT
-- 3.  CLASSIFY_DOCUMENT(VARCHAR) → VARIANT
-- 4.  CHECK_COMPLIANCE(NUMBER) → VARIANT
-- 5.  CROSS_CHECK_DOCUMENTS(NUMBER, NUMBER) → VARIANT
-- 6.  DETECT_DUPLICATES(NUMBER) → VARIANT
-- 7.  ENRICH_DOCUMENT(NUMBER) → VARIANT
-- 8.  SAP_POST_FI_DOCUMENT(NUMBER) → VARIANT
-- 9.  SAP_POST_GOODS_RECEIPT(NUMBER) → VARIANT
-- 10. SAP_CREATE_DELIVERY(NUMBER) → VARIANT
-- 11. SAP_ALLOCATE_COSTS(NUMBER) → VARIANT
-- 12. SCREEN_SANCTIONS(VARCHAR) → VARIANT
-- 13. GET_EXCHANGE_RATE(VARCHAR, VARCHAR, FLOAT) → VARIANT
-- 14. GET_PORT_WEATHER(VARCHAR) → VARIANT
-- 15. GET_TRADE_STATS(VARCHAR) → VARIANT
-- 16. EXTRACT_FROM_IMAGE(VARCHAR, VARCHAR) → VARIANT
-- 17. PARSE_XML_EDI(VARCHAR, VARCHAR) → VARIANT
-- 18. VERIFY_CONTAINER_PHOTO(VARCHAR, VARCHAR) → VARIANT
-- 19. CHAT_WITH_AGENT(VARCHAR, VARCHAR, VARCHAR) → VARIANT
-- 20. QUERY_SHIPMENT_STATS(VARCHAR) → VARCHAR
-- 21. QUERY_SHIPMENT_DETAIL(VARCHAR, VARCHAR) → VARCHAR
-- 22. RUN_ANALYTICS_PIPELINE() → VARIANT [Python]
-- ============================================================================
-- EXPORT SCRIPT: Run this to regenerate individual DDL files
-- ============================================================================

-- Execute these to view full DDL for each procedure:
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.AI_COMPLETE_WITH_RETRY(VARCHAR, VARCHAR, NUMBER, VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.CLASSIFY_DOCUMENT_TEXT(VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.CLASSIFY_DOCUMENT(VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.CHECK_COMPLIANCE(NUMBER)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.CROSS_CHECK_DOCUMENTS(NUMBER, NUMBER)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.DETECT_DUPLICATES(NUMBER)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.ENRICH_DOCUMENT(NUMBER)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.SAP_POST_FI_DOCUMENT(NUMBER)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.SAP_POST_GOODS_RECEIPT(NUMBER)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.SAP_CREATE_DELIVERY(NUMBER)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.SAP_ALLOCATE_COSTS(NUMBER)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.SCREEN_SANCTIONS(VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.GET_EXCHANGE_RATE(VARCHAR, VARCHAR, FLOAT)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.GET_PORT_WEATHER(VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.GET_TRADE_STATS(VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.EXTRACT_FROM_IMAGE(VARCHAR, VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.PARSE_XML_EDI(VARCHAR, VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.VERIFY_CONTAINER_PHOTO(VARCHAR, VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.CHAT_WITH_AGENT(VARCHAR, VARCHAR, VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.QUERY_SHIPMENT_STATS(VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.QUERY_SHIPMENT_DETAIL(VARCHAR, VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'MENDIX_APP.AGENTS.RUN_ANALYTICS_PIPELINE()');

-- FUNCTIONS (8 total):
SELECT GET_DDL('FUNCTION', 'MENDIX_APP.AGENTS.CONVERT_CURRENCY(FLOAT, VARCHAR, VARCHAR)');
SELECT GET_DDL('FUNCTION', 'MENDIX_APP.AGENTS.FN_CALCULATE_DD_FEE(VARCHAR, NUMBER)');
SELECT GET_DDL('FUNCTION', 'MENDIX_APP.AGENTS.GET_SHIPMENT_DETAIL(VARCHAR, VARCHAR)');
SELECT GET_DDL('FUNCTION', 'MENDIX_APP.AGENTS.GET_SHIPMENT_STATS(VARCHAR)');
SELECT GET_DDL('FUNCTION', 'MENDIX_APP.AGENTS.GET_SHIPMENT_STATS(VARCHAR, VARCHAR)');
SELECT GET_DDL('FUNCTION', 'MENDIX_APP.AGENTS.GET_TOKYO_WEATHER_EXTERNAL(NUMBER)');
SELECT GET_DDL('FUNCTION', 'MENDIX_APP.AGENTS.TEST_WEATHER_API()');
